<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PKLTP014" name="Test4" tests="1" failures="0" timestamp="9 Mar 2016 17:01:23 GMT" time="57.268" errors="0">
  <testcase name="@BeforeTest beforeTest" time="0.0" classname="defaultpackage.FamilyDynamicsVerification">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at defaultpackage.FamilyDynamicsVerification.beforeTest(FamilyDynamicsVerification.java:87)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="defaultpackage.FamilyDynamicsVerification">
    <skipped/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="datacomparison" time="0.0" classname="defaultpackage.FamilyDynamicsVerification">
    <skipped/>
  </testcase> <!-- datacomparison -->
</testsuite> <!-- Test4 -->
